# Generates MSSQL Developer for Live Test
version: '3.8'

services:
 netty-live-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: netty-live-mssql
    user: root
    environment:
        TZ: "Europe/Istanbul"
        MSSQL_PID: "Developer"
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "AX123qweASD!"        
    # env_file:
    #   - ./netty-mssql/sqlserver.env
    #   - ./netty-mssql/sapassword.env
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      - ./backups:/var/opt/mssql/backups
    restart: unless-stopped
