services:
  postgres:
    image: postgres:18
    container_name: postgres17-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Europe/Istanbul
      PGTZ: Europe/Istanbul
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 16g
    # Removed cpus and logging for Podman compatibility