version: '3.8'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root
    container_name: netty-mssql-2022
    environment:
      MSSQL_SA_PASSWORD: "AX123qweASD!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      TZ: "Europe/Istanbul"
    ports:
      - 38367:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      - ./backups:/var/opt/mssql/backups
    networks:
      - netty-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "AX123qweASD!", "-Q", "SELECT 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

networks:
   netty-network:
     name: netty-network
     external: true
     driver: bridge
      
