version: "3"

services:

# Redis Part
  netty-redis:
    image: redis:latest
    container_name: netty-redis
    environment:
      - TZ=Europe/Istanbul
    # volumes:
    #   - redis_volume_data:/data
    command: redis-server --requirepass n€tty
    ports:
      - 6379:6379
    networks:
      - netty-network
    restart: always


  netty-redis-commander:
    container_name: netty-redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - TZ=Europe/Istanbul
      - REDIS_HOST=netty-redis
      - REDIS_PASSWORD=n€tty
  #    - REDIS_HOSTS=local:netty-beycelik-redis:6379
    depends_on:
      - netty-redis
    ports:
      - 8081:8081
    networks:
      - netty-network
    restart: always

#Network Creation
networks:
   netty-network:
     name: netty-network
#     external: true
     driver: bridge
     