version: "3"

services:

# Proxies requests to internal services

  # generates NettyApps medical Admin site
  netty-live-medical-admin:
    image: registry.nettyapps.com.tr/netty/angular/admin-portal:live
    container_name: netty-live-medical-admin
    environment:
      - API_URL=https://medical.nettyapps.com.tr/adminapi
      - ADMIN_URL=https://medical.nettyapps.com.tr/login
      - BASE_HREF=/admin/
      - APPLICATION=AdminPortal
      - TZ=Europe/Istanbul
    ports:
      - 8490:80
      - 28490:443
    restart: unless-stopped
    networks:
      - netty-network

  # generates NettyApps medical Admin Api site
  netty-live-medical-adminapi:
    image: registry.nettyapps.com.tr/netty/restapi/admin-portal:live
    container_name: netty-live-medical-adminapi
    environment:
      - CONNECTION_STRING=${DB_CONNECTION_STRING}
      - MAXWRONGTRY=5
      - TIMEOUTDURATION=90
      - TZ=Europe/Istanbul
    depends_on:
      - netty-redis-medical
    ports:
      - 8491:80
      - 28491:443
    cap_add:
      - "NET_BIND_SERVICE"
    restart: unless-stopped
    networks:
      - netty-network

  # generates NettyApps medical Authorization Api site
  netty-live-medical-login:
    image: registry.nettyapps.com.tr/netty/restapi/authorization:live
    container_name: netty-live-medical-login
    environment:
      - CONNECTION_STRING=${DB_CONNECTION_STRING}
      - MAXWRONGTRY=5
      - TIMEOUTDURATION=90
      - TZ=Europe/Istanbul
      - REDIS_CONNECTION=netty-redis:6379,password=nâ‚¬tty
      - REDIS_INSTANCE=Medical_
    ports:
      - 8492:80
      - 28492:443
    cap_add:
      - "NET_BIND_SERVICE"
    restart: unless-stopped
    networks:
      - netty-network

  # generates NettyApps medical Angular site
  netty-live-medical:
    image: registry.nettyapps.com.tr/netty/angular/medical:latest
    container_name: netty-live-medical
    environment:
      - API_URL=https://medical.nettyapps.com.tr/medicalapi
      - ADMIN_URL=https://medical.nettyapps.com.tr/login
      - BASE_HREF=/medical/
      - APPLICATION=Medical
      - TZ=Europe/Istanbul
    ports:
      - 8493:80
      - 28493:443
    restart: unless-stopped
    networks:
      - netty-network

  # generates NettyApps medical Api site
  netty-live-medicalapi:
    image: registry.nettyapps.com.tr/netty/restapi/medical:latest
    container_name: netty-live-medicalapi
    environment:
      - CONNECTION_STRING=${DB_CONNECTION_STRING}
      - MAXWRONGTRY=5
      - TIMEOUTDURATION=90
      - TZ=Europe/Istanbul
      - APPLICATION=Medical
    ports:
      - 8494:80
      - 28494:443
    cap_add:
      - "NET_BIND_SERVICE"
    restart: unless-stopped
    networks:
      - netty-network

  # Redis Part
  # netty-redis-medical:
  #   image: redis:latest
  #   container_name: netty-redis-medical
  #   # volumes:
  #   #   - redis_volume_data:/data
  #   command: --port 6380
  #   ports:
  #     - 6380:6380
  #   restart: always

networks:
   netty-network:
     name: netty-network
     external: true
     driver: bridge
